version: '3.9'
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: front.Dockerfile
      network: host
    ports:
      - "8080:8080"

  backend:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    build:
      context: ./back-end
      dockerfile: back.Dockerfile
      network: host
    ports:
      - "5000:5000"
    volumes:
      - ${SQLITE_ABS_DIR}:/www/sqlite.db
      - ./back-end/app/static/ecg_png_cache:/www/app/static/ecg_png_cache
      - ${ECG_AU_DIR}:${ECG_AU_DIR}

  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #     - "8000:8080"
  #   volumes:
  #     - ./db/design:/var/www/html/designs/hydra
  #   environment:
  #     ADMINER_DEFAULT_SERVER: SQLite
  #     ADMINER_DESIGN: hydra
